modLoader = "javafml"
loaderVersion = "[43,)"
license = "All rights reserved"

[[mods]]
modId = "snakerlib"
version = "${file.jarVersion}"
displayName = "SnakerLib"
authors = "SnakerBone"
description = "SnakerLib is a modding library for SnakerBone's mods"

[[dependencies.snakerlib]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.snakerlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"