
[common]
	#Should ALT + SHIFT + F4 force crash the JVM for debugging purposes (default: false)
	forceCrashJvmKeyBindings = false
	#Should JVM crash files be deleted on startup for optimization purposes (default: true)
	removeJvmCrashFilesOnStartup = true
	#Should Minecraft crash files be deleted on startup for optimization purposes (default: false)
	removeMinecraftCrashFilesOnStartup = false
	#Should Right CTRL + Scroll Lock say goodbye world (default: false)
	goodbyeWorldKeyBindings = false

